name: Bug report
description: Reporta un problema
labels: ["bug"]
body:
  - type: input
    id: contexto
    attributes:
      label: Contexto
      description: Dónde ocurre (repo, módulo, rama).
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
  - type: textarea
    id: real
    attributes:
      label: Resultado real
  - type: textarea
    id: evidencias
    attributes:
      label: Evidencias
      description: URLs a capturas o Drive
